In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/chest-xray-covid19-pneumonia/Data/train/NORMAL/NORMAL(879).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/NORMAL/NORMAL(1073).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/NORMAL/NORMAL(1146).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/NORMAL/NORMAL(324).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/NORMAL/NORMAL(1061).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/NORMAL/NORMAL(812).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/NORMAL/NORMAL(471).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/NORMAL/NORMAL(258).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/NORMAL/NORMAL(594).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/NORMAL/NORMAL(1070).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/NORMAL/NORMAL(723).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/NORMAL/NORMAL(254).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/NORMAL/NORMAL(682)

/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(2580).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(403).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(3131).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(3369).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(739).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(2910).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(744).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(1358).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(3280).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(843).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(632).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(647).jp

/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(2393).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(3097).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(1809).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(1120).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(160).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(3150).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(658).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(2918).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(2048).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(208).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(2531).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(726).

/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(2400).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(1518).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(1934).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(1042).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(2619).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(2149).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(27).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(775).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(2472).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(3370).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(1528).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/train/PNEUMONIA/PNEUMONIA(1837)

/kaggle/input/chest-xray-covid19-pneumonia/Data/test/PNEUMONIA/PNEUMONIA(4229).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/test/PNEUMONIA/PNEUMONIA(4232).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/test/PNEUMONIA/PNEUMONIA(3959).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/test/PNEUMONIA/PNEUMONIA(4271).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/test/PNEUMONIA/PNEUMONIA(3691).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/test/PNEUMONIA/PNEUMONIA(3667).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/test/PNEUMONIA/PNEUMONIA(4028).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/test/PNEUMONIA/PNEUMONIA(3820).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/test/PNEUMONIA/PNEUMONIA(4123).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/test/PNEUMONIA/PNEUMONIA(3897).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/test/PNEUMONIA/PNEUMONIA(4072).jpg
/kaggle/input/chest-xray-covid19-pneumonia/Data/test/PNEUMONIA/PNEUMONIA(3966).jpg
/kag

In [2]:
pip install imutils

  Created wheel for imutils: filename=imutils-0.5.3-py3-none-any.whl size=25850 sha256=2505f10dcf09e2adea62cae771dc05ce71b7b3ef37b9e1d80b28dfe6e922bc4d
  Stored in directory: /root/.cache/pip/wheels/fc/9c/6d/1826267c72afa51b564c9c6e0f66abc806879338bc593a2270
Successfully built imutils
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
import os
import matplotlib.pyplot as plt
import imutils
from imutils import paths

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import AveragePooling2D
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Input
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

In [4]:
dataset='/kaggle/input/chest-xray-covid19-pneumonia/Data/'
imagePaths=list(paths.list_images(dataset))

In [5]:
imagePaths

['/kaggle/input/chest-xray-covid19-pneumonia/Data/train/NORMAL/NORMAL(879).jpg',
 '/kaggle/input/chest-xray-covid19-pneumonia/Data/train/NORMAL/NORMAL(1073).jpg',
 '/kaggle/input/chest-xray-covid19-pneumonia/Data/train/NORMAL/NORMAL(1146).jpg',
 '/kaggle/input/chest-xray-covid19-pneumonia/Data/train/NORMAL/NORMAL(324).jpg',
 '/kaggle/input/chest-xray-covid19-pneumonia/Data/train/NORMAL/NORMAL(1061).jpg',
 '/kaggle/input/chest-xray-covid19-pneumonia/Data/train/NORMAL/NORMAL(812).jpg',
 '/kaggle/input/chest-xray-covid19-pneumonia/Data/train/NORMAL/NORMAL(471).jpg',
 '/kaggle/input/chest-xray-covid19-pneumonia/Data/train/NORMAL/NORMAL(258).jpg',
 '/kaggle/input/chest-xray-covid19-pneumonia/Data/train/NORMAL/NORMAL(594).jpg',
 '/kaggle/input/chest-xray-covid19-pneumonia/Data/train/NORMAL/NORMAL(1070).jpg',
 '/kaggle/input/chest-xray-covid19-pneumonia/Data/train/NORMAL/NORMAL(723).jpg',
 '/kaggle/input/chest-xray-covid19-pneumonia/Data/train/NORMAL/NORMAL(254).jpg',
 '/kaggle/input/chest-xr

In [6]:
data=[]
labels=[]

for i in imagePaths:
    label=i.split(os.path.sep)[-2]
    labels.append(label)
    image=load_img(i,target_size=(224,224))
    image=img_to_array(image)
    image=preprocess_input(image)
    data.append(image)

In [7]:
data

[array([[[-1.        , -1.        , -1.        ],
         [-1.        , -1.        , -1.        ],
         [-1.        , -1.        , -1.        ],
         ...,
         [-0.8509804 , -0.8509804 , -0.8509804 ],
         [-1.        , -1.        , -1.        ],
         [-1.        , -1.        , -1.        ]],
 
        [[-0.88235295, -0.88235295, -0.88235295],
         [-0.8745098 , -0.8745098 , -0.8745098 ],
         [-0.88235295, -0.88235295, -0.88235295],
         ...,
         [-0.8352941 , -0.8352941 , -0.8352941 ],
         [-1.        , -1.        , -1.        ],
         [-1.        , -1.        , -1.        ]],
 
        [[-0.8980392 , -0.8980392 , -0.8980392 ],
         [-0.8666667 , -0.8666667 , -0.8666667 ],
         [-0.8901961 , -0.8901961 , -0.8901961 ],
         ...,
         [-0.85882354, -0.85882354, -0.85882354],
         [-1.        , -1.        , -1.        ],
         [-1.        , -1.        , -1.        ]],
 
        ...,
 
        [[-1.        , -1.        

In [8]:
labels

['NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',
 'NORMAL',

In [9]:
data=np.array(data,dtype='float32')
labels=np.array(labels)

In [10]:
data.shape

(6432, 224, 224, 3)

In [11]:
labels

array(['NORMAL', 'NORMAL', 'NORMAL', ..., 'PNEUMONIA', 'PNEUMONIA',
       'PNEUMONIA'], dtype='<U9')

In [12]:
# Import label encoder 
from sklearn import preprocessing 
  
# label_encoder object knows how to understand word labels. 
label_encoder = preprocessing.LabelEncoder() 
  
# Encode labels in column 'species'. 
lab= label_encoder.fit_transform(labels) 
  

In [13]:
lab

array([1, 1, 1, ..., 2, 2, 2])

In [14]:
from numpy import argmax
from keras.utils import to_categorical

# define example
dat = lab
dat = np.array(dat)
print(dat)
# one hot encode
encoded = to_categorical(dat)
print(encoded)
# invert encoding
inverted = argmax(encoded[0])
print(inverted)

[1 1 1 ... 2 2 2]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 ...
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
1


In [15]:
train_X,test_X,train_Y,test_Y=train_test_split(data,encoded,test_size=0.20,stratify=labels,random_state=10)

In [16]:
train_X.shape

(5145, 224, 224, 3)

In [17]:
train_Y.shape

(5145, 3)

In [18]:
test_X.shape

(1287, 224, 224, 3)

In [19]:
test_Y.shape

(1287, 3)

In [20]:
aug=ImageDataGenerator(rotation_range=20,zoom_range=0.08,width_shift_range=0.1,height_shift_range=0.1,shear_range=0.15,horizontal_flip=True,vertical_flip=True,fill_mode='nearest')

In [21]:
baseModel=MobileNetV2(weights='imagenet',include_top=False,input_tensor=Input(shape=(224,224,3)))

9412608/9406464 [==============================] - 0s 0us/step


In [22]:
baseModel.summary()

Model: "mobilenetv2_1.00_224"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 224, 224, 3) 0                                            
__________________________________________________________________________________________________
Conv1_pad (ZeroPadding2D)       (None, 225, 225, 3)  0           input_1[0][0]                    
__________________________________________________________________________________________________
Conv1 (Conv2D)                  (None, 112, 112, 32) 864         Conv1_pad[0][0]                  
__________________________________________________________________________________________________
bn_Conv1 (BatchNormalization)   (None, 112, 112, 32) 128         Conv1[0][0]                      
_______________________________________________________________________________

In [27]:
headModel=baseModel.output
headModel=AveragePooling2D(pool_size=(7,7))(headModel)
headModel=Flatten(name='Flatten')(headModel)
headModel=Dense(128,activation='relu')(headModel)
headModel=Dropout(0.5)(headModel)
headModel=Dense(3,activation='softmax')(headModel)

model=Model(inputs=baseModel.input,outputs=headModel)

In [28]:
for layer in baseModel.layers:
    layer.trainable=False

In [29]:
model.summary()

Model: "functional_3"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 224, 224, 3) 0                                            
__________________________________________________________________________________________________
Conv1_pad (ZeroPadding2D)       (None, 225, 225, 3)  0           input_1[0][0]                    
__________________________________________________________________________________________________
Conv1 (Conv2D)                  (None, 112, 112, 32) 864         Conv1_pad[0][0]                  
__________________________________________________________________________________________________
bn_Conv1 (BatchNormalization)   (None, 112, 112, 32) 128         Conv1[0][0]                      
_______________________________________________________________________________________

In [32]:
learning_rate=0.001
Epochs=10
BS=12

opt=Adam(lr=learning_rate,decay=learning_rate/Epochs)
model.compile(loss='binary_crossentropy',optimizer=opt,metrics=['accuracy'])

H=model.fit(
    aug.flow(train_X,train_Y,batch_size=BS),
    steps_per_epoch=len(train_X)//BS,
    validation_data=(test_X,test_Y),
    validation_steps=len(test_X)//BS,
    epochs=Epochs
)


model.save(' /kaggle/working/')

Epoch 1/10
428/428 [==============================] - 166s 389ms/step - loss: 0.1505 - accuracy: 0.9129 - val_loss: 0.1115 - val_accuracy: 0.9394
Epoch 2/10
428/428 [==============================] - 137s 319ms/step - loss: 0.1399 - accuracy: 0.9190
Epoch 3/10
428/428 [==============================] - 137s 321ms/step - loss: 0.1283 - accuracy: 0.9262
Epoch 4/10
428/428 [==============================] - 137s 320ms/step - loss: 0.1229 - accuracy: 0.9332
Epoch 5/10
428/428 [==============================] - 136s 318ms/step - loss: 0.1104 - accuracy: 0.9365
Epoch 6/10
428/428 [==============================] - 135s 316ms/step - loss: 0.1143 - accuracy: 0.9363
Epoch 7/10
428/428 [==============================] - 136s 318ms/step - loss: 0.1122 - accuracy: 0.9336
Epoch 8/10
428/428 [==============================] - 137s 321ms/step - loss: 0.1079 - accuracy: 0.9394
Epoch 9/10
428/428 [==============================] - 137s 320ms/step - loss: 0.1028 - accuracy: 0.9421
Epoch 10/10
428/428 [=

In [34]:
from sklearn.metrics import accuracy_score

In [33]:
predict=model.predict(test_X,batch_size=BS)
predict=np.argmax(predict,axis=1)
print(accuracy_score(test_Y.argmax(axis=1),predict))

NameError: name 'lb' is not defined